linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - metalinter
    - performance
    - sql
    - test
    - unused
  disable:
    - contextcheck
    - exhaustruct
    - wrapcheck
